@startuml 会员充值卡顺序图
actor manager 
actor user
group 线下实体卡 创建类型为手动
manager--> 批量充值卡任务中心:访问管理后台，创建充值卡任务设置对应参数
' 管理后台-> 服务端:将管理员填写的充值卡任务发送到服务端

批量充值卡任务中心-> 批量充值卡任务中心:新增充值卡批量生成任务信息
批量充值卡任务中心-> 充值卡中心:根据任务信息批量生成充值卡
manager --> 批量充值卡任务中心:请求导出生成的充值卡
批量充值卡任务中心->充值卡中心:根据任务查询当前充值卡中心充值卡
充值卡中心->批量充值卡任务中心:返回充值卡查询信息
批量充值卡任务中心->manager:返回包含卡号，密码的Excel文件


manager-> 实体卡制造商:印刷制卡
实体卡制造商-> manager:制卡完成，交回


manager--> 批量充值卡任务中心:访问管理后台，设置批量充值卡激活（激活按钮）

' 管理后台 -> 服务端:携带批号请求服务端

批量充值卡任务中心-> 批量充值卡任务中心:修改充值卡批量生成任务状态
批量充值卡任务中心-> 充值卡中心:修改该批量生成任务下所有充值卡的激活状态和激活时间



user-> 充值卡中心:使用账号密码充值
充值卡中心 ->批量充值卡任务中心:查询该批次充值卡是否投入使用


end

group 线上虚拟卡 创建类型为自动
manager--> 批量充值卡任务中心:访问管理后台，创建充值卡任务设置对应参数
批量充值卡任务中心-> 批量充值卡任务中心:新增充值卡批量生成任务信息
user-> 批量充值卡任务中心:找到对应的线上充值卡批量任务信息
批量充值卡任务中心 ->充值卡中心:创建充值卡
支付中心->充值卡中心:通知充值卡中心激活充值卡状态（之后激活之后才能自己使用或者分享给其他人使用）
user->充值卡中心:用户携带参数充值
end
充值卡中心 ->充值卡中心:查询该充值卡是否处于可用状态
充值卡中心 ->充值卡中心:创建该充值卡的充值记录，并修改充值卡状态
充值卡中心 ->充值卡中心:向积分中心发送充值请求，并确认回执后事物完成

@enduml

