@startuml 支付系统
actor user
user-> 订单: 生成订单
订单->支付: 去支付
支付->支付:选择支付方式，保存支付订单
group 三方支付单位
    支付->三方支付公司:发送支付信息到第三方支付系统下单
    三方支付公司-->支付:返回预付单信息
end
支付<-->订单:校验(异步)
支付-->user:返回预支付信息
user->user:通过预付单回执信息，发起支付(第三方)
user->订单:支付成功，修改订单状态
三方支付公司-->支付:异步回执支付信息（平台积分支付回执）
group 支付结果
    支付-->支付:收到渠道成功应答（异步），保存支付回执
    支付-->支付:更新支付订单状态
end
group 如果需要设置账期的话
    支付->支付:设置账期
    支付->支付:向商户中心设置商户虚拟账户余额
end
支付->分账: 查询核定交易分润
分账->分账: 生成分账主单，生成各个中心分帐明细
actor store
group 二清结算
    分账->结算:操作平台商户虚拟账户余额


end
group 一清结算
    分账->三方支付公司:分账（调用银盛的分账接口，银盛内部划拨虚拟账户）
    分账<--三方支付公司:分账通知（同步）
    分账<-三方支付公司:分账完成通知（异步）
end
actor store
group 提现流程
    store->结算:发起提现请求
    结算->结算:创建提现申请主表
    结算->结算:统计金额渠道成分，
    结算->三方支付公司:发起转账请求
    三方支付公司-->结算:返回转账结果
end
@enduml