@startuml
actor manage


manage->订单路由配置中心:管理员注册需要通过订单中心路由的业务订单中心

订单路由配置中心->订单路由配置中心:记录路由信息，并生成密钥信息

actor user

user->订单中心:用户下单,携带对应服务中心的密钥信息请求下单

group 订单中心业务验证
订单中心->订单中心:解析密钥信息

订单中心->订单路由配置中心:通过解析内容到订单路由配置中心确认

订单路由配置中心-->订单中心:返回正确的路由登记信息确认

订单中心->订单中心:通过路由信息逻辑处理该如何调用接口
note right:这个地方很麻烦，需要统一接口实现，路由判断接口
end 
group 业务逻辑操作
订单中心->业务订单中心:调用下单接口,到对应的业务中心下单
订单中心->业务订单中心:调用修改状态接口,到对应的业务中心修改订单状态
业务订单中心-->订单中心:返回订单下单成功
订单中心-->user:返回给前端用户
end


其他内部中心模块->订单中心: 携带对应服务中心的密钥信息请求订单查询业务
group 订单中心业务验证
订单中心->订单中心:解析密钥信息

订单中心->订单路由配置中心:通过解析内容到订单路由配置中心确认

订单路由配置中心-->订单中心:返回正确的路由登记信息确认

订单中心->订单中心:通过路由信息逻辑处理该如何调用接口
note right:这个地方很麻烦，需要统一接口实现，路由判断接口
end 

group 业务逻辑查询
订单中心->业务订单中心:查询对应业务中心的信息
业务订单中心-->订单中心:返回查询信息
订单中心-->其他内部中心模块:返回详细信息
end




@enduml